import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

//components
import Navbar from '../../components/Navbar'
import Perfil from '../../components/Perfil'
import Skills from '../../components/Skills'
import Projects from '../../components/Projects'
import Contact from '../../components/Contact'


export default function Home() {
  return (
    <>
      <Head>
        <title>Thiago ibiapina - new</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Navbar />
      <Perfil />
      <Skills />
      <Projects />
      <Contact />
      </div>
    </>
  )
}
